### ISSUE TITLE
Suggestion - Themes

### ISSUE THREAD

**Issue by sgtprosper** [JoshuaCaputo/casinocoin-chrome-extension#1]
Hey, the extension looks awsome! I just wanted to come with a suggestion about the themes.  I was thinking black/ or dark theme would look really good? Also, have a little switch easily accessible from within the extension would be super cool. 
Thanks for your effort

**Comment by JoshuaCaputo** [comment]
@sgtprosper ,

Great suggestion! I think this would be an awesome enhancement as well and will begin incorporating themes into the next release. A dark theme is a perfect alternative.

Thanks again!
